### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by scoutante112** [HumaneWolf/WolfVTCStandalone#1]
Hello! I was thinking of starting to work a little on this for a vtc in Sweden that is about to open. But I can't find any sql. Are there any?

**Comment by HumaneWolf** [comment]
If it's not in the repository, I probably don't have it anymore.

Besides that, I don't recommend building on this. It's in a very early state, and does not use any framework to help you out.

I recommend starting from scratch with a framework like Laravel or Asp.net Core, or using an existing finished solution instead.
